CREATE TABLE IF NOT EXISTS `grades` (
  `id`        	   INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `grade`		       VARCHAR(20) NOT NULL,
  CONSTRAINT unique_grade UNIQUE (grade)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;